version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 8
    groups:
      github-actions:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
    groups:
      pub:
        patterns: ["*"]
        update-types: ["minor", "patch"]
